// AUTO-GENERATED by scripts/_gen-set18-traits.ts — do not hand-edit.
//
// TEMPORARY. Set 18 launched with CDragon's TFT extractor unable to read the
// new data format: it published the set's traits, items and augments but only
// 2 of its 74 champions, and crucially NO champion-to-trait links — a mapping
// that exists in no public source (checked: cdragon tft json, cdragon pbe,
// map22.bin.json raw, Data Dragon tft-champion/tft-trait).
//
// So the links were transcribed from the in-game client by hand and resolved
// against real ids here. Champions, costs and icons still come from map22,
// which IS current; only this one mapping is human-sourced.
//
// DELETE THIS FILE once `npx tsx scripts/_set-readiness.ts` reports READY — the
// loader prefers real trait data whenever the source provides it, so a stale
// copy is inert rather than harmful, but it should not outlive its reason.
//
// Generated 2026-08-27 — 74/74 champions.

export const SET18_TRAITS: Record<string, string[]> = {
  DA_18_Ahri: ['DA_18_Blossom', 'DA_18_Spellweaver'], // Ahri (cost 4)
  DA_18_Akali_AD: ['DA_18_Adaptor', 'DA_18_Inferno', 'DA_18_Slayer'], // Akali (cost 1)
  DA_18_Alistar: ['DA_18_Brawler', 'DA_18_Elderwood'], // Alistar (cost 2)
  DA_18_Alune: ['DA_18_Lunar', 'DA_18_Spellweaver', 'DA_AluneUniqueTrait18'], // Alune (cost 5)
  DA_18_Aphelios: ['DA_18_Lunar', 'DA_18_Rapidfire'], // Aphelios (cost 4)
  DA_18_Ashe: ['DA_18_Blossom', 'DA_18_Hunter'], // Ashe (cost 5)
  DA_18_Azir: ['DA_18_Blackthorn', 'DA_18_Executioner', 'DA_18_Summoner'], // Azir (cost 3)
  DA_18_Caitlyn: ['DA_18_Coven', 'DA_18_Hunter'], // Caitlyn (cost 2)
  DA_18_Camille: ['DA_18_Coven', 'DA_18_Slayer'], // Camille (cost 1)
  DA_18_Cassiopeia: ['DA_18_Coven', 'DA_18_Spellweaver'], // Cassiopeia (cost 3)
  DA_18_Diana: ['DA_18_Lunar', 'DA_18_Slayer', 'DA_18_Vanguard'], // Diana (cost 3)
  DA_18_ElderDragon: ['DA_18_ApexPredator'], // Elder Dragon (cost 5)
  DA_18_Elise: ['DA_18_Coven', 'DA_18_Vanguard'], // Elise (cost 2)
  DA_18_Ezreal: ['DA_18_Elderwood', 'DA_18_Executioner'], // Ezreal (cost 4)
  DA_18_GnarSmall: ['DA_18_Brawler', 'DA_18_Elderwood', 'DA_18_Sprykin'], // Gnar (cost 5)
  DA_18_Hecarim: ['DA_18_Elderwood', 'DA_18_Vanguard'], // Hecarim (cost 3)
  DA_18_Ivern: ['DA_18_Greenfather'], // Ivern (cost 5)
  DA_18_Kayle: ['DA_18_Rapidfire', 'DA_18_Solar'], // Kayle (cost 2)
  DA_18_Kennen: ['DA_18_Executioner', 'DA_18_Inferno'], // Kennen (cost 5)
  DA_18_KhaZix: ['DA_18_Rival'], // Kha'Zix (cost 3)
  DA_18_Kobuko: ['DA_18_Brawler', 'DA_18_Sprykin'], // Kobuko (cost 1)
  DA_18_LeBlanc: ['DA_18_Elderwood', 'DA_18_Spellweaver'], // LeBlanc (cost 2)
  DA_18_Leona: ['DA_18_Defender', 'DA_18_Solar'], // Leona (cost 1)
  DA_18_Lillia: ['DA_18_Defender', 'DA_18_Fae'], // Lillia (cost 4)
  DA_18_Lux_Coven: ['DA_18_Coven', 'DA_18_LuxUniqueTrait'], // Lux (Coven) (cost 5)
  DA_18_Lux_Elderwood: ['DA_18_Elderwood', 'DA_18_LuxUniqueTrait'], // Lux (Elderwood) (cost 5)
  DA_18_Lux_Fae: ['DA_18_Fae', 'DA_18_LuxUniqueTrait'], // Lux (Fae) (cost 5)
  DA_18_Lux_Inferno: ['DA_18_Inferno', 'DA_18_LuxUniqueTrait'], // Lux (Inferno) (cost 5)
  DA_18_Lux_Moonbeam: ['DA_18_Lunar', 'DA_18_LuxUniqueTrait'], // Lux (Lunar) (cost 5)
  DA_18_Lux_Primal: ['DA_18_LuxUniqueTrait', 'DA_Primal18'], // Lux (Primal) (cost 5)
  DA_18_Lux_Sunbeam: ['DA_18_LuxUniqueTrait', 'DA_18_Solar'], // Lux (Solar) (cost 5)
  DA_18_Malphite: ['DA_18_Battlemage'], // Malphite (cost 4)
  DA_18_Maokai: ['DA_18_Maokai_UniqueTrait'], // Maokai (cost 5)
  DA_18_MasterYi_AD: ['DA_18_Adaptor', 'DA_18_Blossom'], // Master Yi (cost 3)
  DA_18_Morgana: ['DA_18_Coven', 'DA_18_Invoker'], // Morgana (cost 4)
  DA_18_Ornn: ['DA_18_Defender', 'DA_18_Elderwood'], // Ornn (cost 1)
  DA_18_Rakan: ['DA_18_Fae', 'DA_18_Vanguard', 'DA_Juggernaut18'], // Rakan (cost 1)
  DA_18_Rammus: ['DA_18_Defender', 'DA_18_Sprykin'], // Rammus (cost 3)
  DA_18_RekSai: ['DA_18_Blackthorn', 'DA_18_Brawler'], // Rek'Sai (cost 1)
  DA_18_Rengar: ['DA_18_Rival'], // Rengar (cost 3)
  DA_18_Sejuani: ['DA_18_Solar', 'DA_Juggernaut18'], // Sejuani (cost 2)
  DA_18_Sentry: ['DA_18_Invoker', 'DA_Riftbeast18'], // Pebbles (cost 1)
  DA_18_Sett: ['DA_18_Blossom', 'DA_18_Brawler'], // Sett (cost 4)
  DA_18_Shen: ['DA_18_Defender', 'DA_18_Inferno'], // Shen (cost 2)
  DA_18_Sivir: ['DA_18_Hunter', 'DA_Primal18'], // Sivir (cost 4)
  DA_18_Soraka: ['DA_18_Executioner', 'DA_FloraFatalis18'], // Soraka (cost 4)
  DA_18_Teemo: ['DA_18_Invoker', 'DA_18_Sprykin'], // Teemo (cost 2)
  DA_18_Tristana: ['DA_18_Fae', 'DA_18_Hunter', 'DA_18_Sprykin'], // Tristana (cost 3)
  DA_18_Varus: ['DA_18_Inferno', 'DA_18_Rapidfire'], // Varus (cost 1)
  DA_18_Veigar: ['DA_18_Blackthorn', 'DA_18_Spellweaver', 'DA_18_Sprykin'], // Veigar (cost 1)
  DA_18_Warwick: ['DA_18_Blackthorn', 'DA_18_Slayer'], // Warwick (cost 2)
  DA_18_Xayah: ['DA_18_Elderwood', 'DA_18_Fae', 'DA_18_Rapidfire'], // Xayah (cost 1)
  DA_18_Yorick: ['DA_18_Blossom', 'DA_18_Summoner', 'DA_Juggernaut18'], // Yorick (cost 1)
  DA_18_Yunara: ['DA_18_Blossom', 'DA_18_Executioner'], // Yunara (cost 2)
  DA_18_Zyra: ['DA_18_ZyraUniqueTrait'], // Zyra (cost 4)
  DA_Amumu18: ['DA_18_Inferno', 'DA_Juggernaut18'], // Amumu (cost 4)
  DA_Brambleback18: ['DA_18_Slayer', 'DA_Riftbeast18'], // Brambleback (cost 4)
  DA_Cinderling18: ['DA_18_Hunter', 'DA_Riftbeast18'], // Cinderling (cost 1)
  DA_CrimsonRaptor18: ['DA_18_Rapidfire', 'DA_18_Summoner', 'DA_Riftbeast18'], // Mama Beak (cost 3)
  DA_Draven18: ['DA_DravenUniqueTrait18'], // Draven (cost 5)
  DA_Fiddlesticks18: ['DA_18_Defender', 'DA_18_Spellweaver', 'DA_FloraFatalis18'], // Fiddlesticks (cost 3)
  DA_Gromp18_AP: ['DA_18_Adaptor', 'DA_Riftbeast18'], // Gromp (cost 2)
  DA_Karma18: ['DA_18_Blossom', 'DA_18_Spellweaver'], // Karma (cost 1)
  DA_KogMaw18_AD: ['DA_18_Caustic'], // Kog'Maw (cost 3)
  DA_Krug18: ['DA_18_Brawler', 'DA_Riftbeast18'], // Krug (cost 3)
  DA_Lux18_Base: ['DA_18_LuxUniqueTrait'], // Lux (cost 5)
  DA_Lux18_Blackthorn: ['DA_18_Blackthorn', 'DA_18_LuxUniqueTrait'], // Lux (Blackthorn) (cost 5)
  DA_Lux18_Blossom: ['DA_18_Blossom', 'DA_18_LuxUniqueTrait'], // Lux (Blossom) (cost 5)
  DA_Murkwolf18: ['DA_18_Slayer', 'DA_Riftbeast18'], // Murkwolf (cost 2)
  DA_Nidalee18_AP: ['DA_18_Adaptor', 'DA_Primal18'], // Nidalee (cost 4)
  DA_Scuttlecrab18: ['DA_Juggernaut18', 'DA_Riftbeast18'], // Scuttlecrab (cost 2)
  DA_Sentinel18: ['DA_18_Invoker', 'DA_18_Vanguard', 'DA_Riftbeast18'], // Sentinel (cost 4)
  DA_Taric18: ['DA_Emerald18'], // Taric (cost 5)
  DA_Vi18: ['DA_Juggernaut18', 'DA_Primal18'], // Vi (cost 3)
};
